"""add_batch_remark_to_card_codes

Revision ID: 246d8b8a6d5e
Revises: 9e6b13b3db8e
Create Date: 2026-05-05 22:21:00.470217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246d8b8a6d5e'
down_revision: Union[str, None] = '9e6b13b3db8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_codes', sa.Column('batch_remark', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_codes', 'batch_remark')
    # ### end Alembic commands ###
