"""add_palm_features_to_report

Revision ID: 2f912f8db73a
Revises: 1a5de3b50386
Create Date: 2026-05-04 13:27:52.369993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f912f8db73a'
down_revision: Union[str, None] = '1a5de3b50386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('palm_features', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'palm_features')
    # ### end Alembic commands ###
