"""add_birth_place_and_core_intention

Revision ID: 7bf998c9bcc0
Revises: b9002e01a2e0
Create Date: 2026-05-05 21:41:41.108839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf998c9bcc0'
down_revision: Union[str, None] = 'b9002e01a2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('birth_place', sa.String(length=100), nullable=True))
    op.add_column('reports', sa.Column('core_intention', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'core_intention')
    op.drop_column('reports', 'birth_place')
    # ### end Alembic commands ###
