"""add_is_exported_to_card_codes

Revision ID: 9e6b13b3db8e
Revises: 7bf998c9bcc0
Create Date: 2026-05-05 22:12:00.240476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6b13b3db8e'
down_revision: Union[str, None] = '7bf998c9bcc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_codes', sa.Column('is_exported', sa.SmallInteger(), server_default='0', nullable=True))
    op.add_column('card_codes', sa.Column('exported_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_codes', 'exported_at')
    op.drop_column('card_codes', 'is_exported')
    # ### end Alembic commands ###
