"""add_location_mbti_calendar_zodiac_to_report

Revision ID: 9efc1eeecc89
Revises: 2f912f8db73a
Create Date: 2026-05-04 16:10:00.496362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9efc1eeecc89'
down_revision: Union[str, None] = '2f912f8db73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('reports', sa.Column('mbti', sa.String(length=10), nullable=True))
    op.add_column('reports', sa.Column('calendar_type', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('zodiac', sa.String(length=20), nullable=True))
    op.alter_column('reports', 'user_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=512),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('reports', 'left_hand_image',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('reports', 'right_hand_image',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'right_hand_image',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=512),
               existing_nullable=True)
    op.alter_column('reports', 'left_hand_image',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=512),
               existing_nullable=True)
    op.alter_column('reports', 'user_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=512),
               existing_nullable=True)
    op.drop_column('reports', 'zodiac')
    op.drop_column('reports', 'calendar_type')
    op.drop_column('reports', 'mbti')
    op.drop_column('reports', 'location')
    # ### end Alembic commands ###
