<template>
  <div class="min-h-screen bg-slate-950 text-slate-200 selection:bg-amber-500/30">
    <!-- Loading State -->
    <AnalysisLoading 
      v-if="loading" 
      :progress="currentProgress" 
      :statusText="currentStatusText" 
    />

    <!-- Report Content -->
    <div v-else-if="report" class="report-container pb-32">
      <!-- Sticky Header for Scroll -->
      <div class="sticky top-0 z-30 bg-slate-950/80 backdrop-blur-md border-b border-slate-800 p-4 flex items-center justify-between">
        <button @click="$router.push('/')" class="text-slate-400">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
          </svg>
        </button>
        <h2 class="text-sm font-serif text-amber-200 tracking-widest uppercase">{{ userStore.name }} · 星纹解析</h2>
        <button @click="shareReport" class="text-amber-400">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 100-2.684 3 3 0 000 2.684zm0 9a3 3 0 100-2.684 3 3 0 000 2.684z" />
          </svg>
        </button>
      </div>

      <!-- Hero Header -->
      <div class="report-hero relative pt-12 pb-8 px-8 text-center overflow-hidden">
        <div class="absolute inset-0 bg-gradient-to-b from-amber-500/10 to-transparent"></div>
        <div class="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full bg-[url('https://www.transparenttextures.com/patterns/stardust.png')] opacity-20"></div>
        
        <div class="relative z-10">
          <div class="w-20 h-20 mx-auto mb-4 rounded-full border-2 border-amber-500/30 p-1">
            <div class="w-full h-full rounded-full bg-slate-800 flex items-center justify-center text-3xl shadow-inner">📜</div>
          </div>
          <h1 class="text-2xl font-serif font-bold mb-2 text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-amber-500">
            星纹全息命理报告
          </h1>
          <div class="flex items-center justify-center gap-3 text-amber-500/60 text-[10px] tracking-[0.2em] uppercase">
            <span>{{ report ? report.gender : userStore.gender }}</span>
            <span class="w-1 h-1 rounded-full bg-amber-500/30"></span>
            <span>{{ report ? formatBirthDate(report.birthday) : formatBirthDateFromStore() }}</span>
          </div>
          <p class="mt-6 text-slate-500 text-[9px] uppercase tracking-widest">
            Generated by Xingwen AI · {{ formatDate(report.created_at) }}
          </p>
        </div>
      </div>

      <!-- Main Content -->
      <div class="report-body px-5 space-y-6">
        <!-- Download Hint Tip (Highly Visible) -->
        <div class="mb-6 p-3.5 rounded-2xl bg-gradient-to-r from-amber-500/20 to-amber-600/10 border-2 border-amber-500/30 shadow-[0_0_20px_rgba(245,158,11,0.15)] flex items-start gap-3.5 relative overflow-hidden group">
          <!-- Background Decoration -->
          <div class="absolute -right-4 -top-4 w-16 h-16 bg-amber-500/10 rounded-full blur-2xl group-hover:bg-amber-500/20 transition-colors"></div>
          
          <div class="flex-shrink-0 w-9 h-9 rounded-xl bg-gradient-to-br from-amber-400 to-amber-600 flex items-center justify-center text-slate-950 shadow-lg shadow-amber-500/20 animate-bounce">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          
          <div class="flex-1 space-y-0.5">
            <h4 class="text-amber-200 font-serif font-bold text-xs flex items-center gap-2">
              <span class="relative flex h-2 w-2">
                <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75"></span>
                <span class="relative inline-flex rounded-full h-2 w-2 bg-amber-500"></span>
              </span>
              深度解析已就绪
            </h4>
            <p class="text-[11px] text-slate-300 leading-relaxed">
              完整 <span class="text-amber-400 font-bold underline underline-offset-4 decoration-amber-500/50">PDF 深度解析报告</span> 请滑动至页面 <span class="text-amber-400 font-bold underline underline-offset-4 decoration-amber-500/50">底部</span> 下载。
            </p>
          </div>
        </div>

        <div 
          v-for="(section, index) in sections" 
          :key="index"
          class="section-card group"
        >
          <div 
            class="flex items-center gap-4 mb-2"
          >
            <div class="w-8 h-8 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-center text-amber-500">
              <span class="text-xs font-serif">{{ (index + 1).toString().padStart(2, '0') }}</span>
            </div>
            <h3 class="flex-1 text-lg font-serif font-bold text-amber-100/90">
              {{ section.chapter_title }}
            </h3>
          </div>
          
          <div class="pl-12">
            <!-- Highlights -->
            <div v-if="section.highlights && section.highlights.length > 0" class="flex flex-wrap gap-2 mb-3">
              <span 
                v-for="tag in section.highlights" 
                :key="tag"
                class="px-2 py-1 rounded-md bg-amber-500/10 border border-amber-500/20 text-xs text-amber-400 font-medium tracking-wider"
              >
                {{ tag }}
              </span>
            </div>
            
            <!-- First Paragraph + Ellipsis -->
            <div v-if="section.paragraphs && section.paragraphs.length > 0" class="mt-2">
              <p class="text-slate-400 text-sm leading-relaxed line-clamp-3">
                {{ section.paragraphs[0] }}
                <span v-if="section.paragraphs.length > 1" class="text-amber-500/50">...</span>
              </p>
            </div>
            <div v-else-if="(!section.highlights || section.highlights.length === 0)" class="text-slate-500 text-xs italic">
              该章节精华已汇入总纲
            </div>
          </div>
        </div>

        <!-- Word Count & PDF Guide -->
        <div class="mt-12 p-6 rounded-2xl bg-gradient-to-b from-slate-900 to-slate-950 border border-amber-500/20 text-center">
          <div class="inline-block p-3 rounded-full bg-amber-500/10 mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.232.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5S19.832 5.477 21 6.253v13C19.832 18.477 18.246 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
            </svg>
          </div>
          <h4 class="text-lg font-serif font-bold text-amber-200 mb-2">详细报告已生成</h4>
          <p class="text-slate-400 text-sm leading-relaxed mb-6">
            您的星纹全息报告共计 <span class="text-amber-400 font-bold">{{ totalWordCount }}</span> 字。<br>
            以上仅展示了各章节的核心精要，详细的深度解析与改运建议已整理为 PDF 文档。
          </p>
          <button 
            @click="handleDownloadPDF"
            class="w-full py-3 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-400 text-sm font-bold hover:bg-amber-500/20 transition-all"
          >
            下载详细 PDF 报告
          </button>
        </div>
      </div>

      <!-- Floating Action Button -->
      <div class="fixed bottom-8 left-1/2 -translate-x-1/2 w-full max-w-xs px-4 z-40">
        <button 
          @click="shareReport"
          class="w-full bg-gradient-to-r from-amber-400 to-amber-600 text-slate-950 py-4 rounded-2xl font-bold shadow-[0_10px_30px_rgba(251,191,36,0.3)] flex items-center justify-center gap-3 active:scale-95 transition-transform"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clip-rule="evenodd" />
          </svg>
          生成星辰海报
        </button>
      </div>
    </div>

    <!-- Error State -->
    <div v-else-if="error" class="min-h-screen flex flex-col items-center justify-center p-8 text-center bg-slate-900">
      <div class="w-20 h-20 bg-red-500/10 rounded-full flex items-center justify-center text-4xl mb-6">💫</div>
      <h2 class="text-2xl font-serif font-bold mb-4 text-red-200">解析过程遇到了波动</h2>
      <p class="text-slate-400 text-sm mb-10 leading-relaxed max-w-xs">{{ error }}</p>
      <button 
        @click="retry" 
        class="bg-slate-800 text-white px-10 py-4 rounded-xl font-bold border border-slate-700 active:bg-slate-700 transition-colors"
      >
        重新开始
      </button>
    </div>

    <!-- Poster Modal -->
    <PosterModal 
      v-model:show="showPoster"
      :name="userStore.name"
      :gender="userStore.gender"
      :birthday="`${userStore.birthday} ${userStore.birthTime}`"
      :reportContent="report?.content || ''"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, toRaw, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useUserStore } from '../stores/user'
import { useReportStore } from '../stores/report'
import AnalysisLoading from '../components/AnalysisLoading.vue'
import PosterModal from '../components/PosterModal.vue'
import axios from 'axios'
import { marked } from 'marked'

const route = useRoute()
const router = useRouter()
const userStore = useUserStore()
const reportStore = useReportStore()

const loading = ref(true)
const report = ref<any>(null)
const error = ref('')
const currentProgress = ref(0)
const currentStatusText = ref('正在连接星辰...')
const showPoster = ref(false)

const sections = ref<any[]>([])

const totalWordCount = computed(() => {
  if (!report.value || !report.value.content) return 0
  return report.value.content.length
})

const handleDownloadPDF = async () => {
  if (!report.value || !report.value.id) return
  
  try {
    const reportId = report.value.id
    const baseUrl = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1'
    const downloadUrl = `${baseUrl}/report/${reportId}/pdf`
    
    // 创建一个隐藏的 a 标签并触发下载
    const link = document.createElement('a')
    link.href = downloadUrl
    link.setAttribute('download', `星纹报告_${userStore.name}.pdf`)
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  } catch (err) {
    console.error('PDF Download Error:', err)
    alert('下载 PDF 失败，请稍后重试。')
  }
}

const renderMarkdown = (content: string) => {
  return marked(content)
}

const formatBirthDate = (dateStr: string) => {
  if (!dateStr) return '-'
  const date = new Date(dateStr)
  const datePart = `${date.getFullYear()}-${(date.getMonth() + 1).toString().padStart(2, '0')}-${date.getDate().toString().padStart(2, '0')}`
  
  if (date.getSeconds() === 1) {
    return `${datePart} (出生时间未知)`
  }
  
  const timePart = `${date.getHours().toString().padStart(2, '0')}:${date.getMinutes().toString().padStart(2, '0')}`
  return `${datePart} ${timePart}`
}

const formatBirthDateFromStore = () => {
  if (!userStore.birthday) return '-'
  return `${userStore.birthday} ${userStore.birthTime || '(出生时间未知)'}`
}

const formatDate = (dateStr: string) => {
  if (!dateStr) return '-'
  const date = new Date(dateStr)
  
  // 如果秒数是 1，说明是后端标记的“时间未知”
  if (date.getSeconds() === 1) {
    return `${date.getFullYear()}.${(date.getMonth() + 1).toString().padStart(2, '0')}.${date.getDate().toString().padStart(2, '0')} (出生时间未知)`
  }
  
  return `${date.getFullYear()}.${(date.getMonth() + 1).toString().padStart(2, '0')}.${date.getDate().toString().padStart(2, '0')} ${date.getHours().toString().padStart(2, '0')}:${date.getMinutes().toString().padStart(2, '0')}`
}

const parseSections = (content: string) => {
  const sectionTitles = [
    '卷首语', '第一章', '第二章', '第三章', '第四章', '第五章', '第六章', '第七章', '结语'
  ]
  
  const results = []
  const matches: any[] = []
  
  // 更加宽容但定位准确的正则：
  // 1. 允许行首有 #, *, - 等 Markdown 符号
  // 2. 匹配“第X章”或“卷首语/结语”
  // 3. 必须是该行的核心关键词
  sectionTitles.forEach(title => {
    // 匹配模式：(行首或换行) + (可选非字母数字符号如#*) + (标题) + (可选符号或空格或换行)
    const regex = new RegExp(`(?:^|\\n)[\\s#*>-]*(${title})(?:[:：\\s*\\n]|$)`, 'g')
    let m
    while ((m = regex.exec(content)) !== null) {
      matches.push({
        title: title,
        index: m.index,
        fullMatch: m[0]
      })
    }
  })
  
  // 按出现位置排序
  matches.sort((a, b) => a.index - b.index)
  
  // 过滤重复和交叉匹配
  const uniqueMatches = []
  let lastEnd = -1
  for (const m of matches) {
    if (m.index >= lastEnd) {
      uniqueMatches.push(m)
      lastEnd = m.index + m.fullMatch.length
    }
  }

  if (uniqueMatches.length === 0) {
    return [{ 
      chapter_title: '深度解析报告', 
      paragraphs: content.trim().split('\n\n'), 
      highlights: [],
      expanded: true 
    }]
  }
  
  for (let i = 0; i < uniqueMatches.length; i++) {
    const current = uniqueMatches[i]
    const next = uniqueMatches[i + 1]
    
    const startIdx = current.index
    const endIdx = next ? next.index : content.length
    
    const fullSection = content.substring(startIdx, endIdx).trim()
    
    // 提取第一行作为标题，其余作为内容
    const lines = fullSection.split('\n')
    let titleLine = lines[0].trim()
    
    // 清理标题行：去除前导的 #, *, > 等
    titleLine = titleLine.replace(/^[\\s#*>-]+/, '').replace(/[\\s#*>-]+$/, '')
    
    const sectionContent = lines.slice(1).join('\n').trim()
    
    results.push({
      chapter_title: titleLine || current.title,
      paragraphs: sectionContent.split('\n\n').filter(p => p.trim()),
      highlights: [],
      expanded: i < 2
    })
  }
  
  return results
}

// 将 base64 转换为 File 的辅助函数
const base64ToFile = (base64String: string, filename: string) => {
  const arr = base64String.split(',')
  const mime = arr[0].match(/:(.*?);/)?.[1] || 'image/jpeg'
  const bstr = atob(arr[1])
  let n = bstr.length
  const u8arr = new Uint8Array(n)
  while (n--) {
    u8arr[n] = bstr.charCodeAt(n)
  }
  return new File([u8arr], filename, { type: mime })
}

const uploadImages = async () => {
  currentStatusText.value = '正在上传手相图片...'
  currentProgress.value = 5
  const uploadPromises = []
  const results: { left?: string, right?: string } = {}

  // 辅助函数：获取可用的文件对象
  const getFileObject = (file: any, preview: string | null, side: string) => {
    if (file && (file instanceof File || file instanceof Blob)) {
      return file
    }
    if (preview && preview.startsWith('data:image')) {
      console.log(`Fallback: Converting base64 to file for ${side} hand`)
      return base64ToFile(preview, `${side}_hand.jpg`)
    }
    return null
  }

  const leftFile = getFileObject(toRaw(userStore.leftHandFile), userStore.leftHandImage, 'left')
  const rightFile = getFileObject(toRaw(userStore.rightHandFile), userStore.rightHandImage, 'right')

  if (leftFile) {
    const formData = new FormData()
    formData.append('file', leftFile)
    uploadPromises.push(
      axios.post('/image/upload', formData, {
        baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1'
      }).then(res => results.left = res.data.filename)
    )
  }

  if (rightFile) {
    const formData = new FormData()
    formData.append('file', rightFile)
    uploadPromises.push(
      axios.post('/image/upload', formData, {
        baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1'
      }).then(res => results.right = res.data.filename)
    )
  }

  if (uploadPromises.length > 0) {
    try {
      await Promise.all(uploadPromises)
      // 更新 store 中的文件名为服务器返回的文件名
      userStore.setUserInfo({
        leftHandImage: results.left || userStore.leftHandImage,
        rightHandImage: results.right || userStore.rightHandImage,
        leftHandFile: null,
        rightHandFile: null
      })
      currentProgress.value = 10
    } catch (err) {
      error.value = '图片上传失败，请检查网络连接'
      throw err
    }
  } else {
    // 如果已经有了文件名（说明已经上传过），则跳过
    if (userStore.leftHandImage && !userStore.leftHandImage.startsWith('data:') &&
        userStore.rightHandImage && !userStore.rightHandImage.startsWith('data:')) {
      currentProgress.value = 10
      return
    }
    throw new Error('缺失手相图片文件，请重新上传')
  }
}

const generateReport = async () => {
  // 检查必要数据是否存在
  if (!userStore.leftHandImage || !userStore.rightHandImage || !userStore.cardCode) {
    error.value = '检测到信息不完整，请重新上传手相并验证卡密。'
    loading.value = false
    setTimeout(() => router.push('/'), 3000)
    return
  }

  try {
    // 只有在生成报告前才真正上传图片
    await uploadImages()

    currentStatusText.value = '正在开启星辰之门...'
    const res = await axios.post('/report/generate', {
      name: userStore.name,
      gender: userStore.gender,
      birthday: `${userStore.birthday} ${userStore.birthTime}`,
      focus_area: userStore.focusArea,
      location: userStore.location,
      mbti: userStore.mbti,
      calendar_type: userStore.calendarType,
      zodiac: userStore.zodiac,
      bazi: userStore.bazi,
      bazi_favorable_elements: userStore.baziFavorableElements,
      left_hand_image: userStore.leftHandImage,
      right_hand_image: userStore.rightHandImage,
      card_code: userStore.cardCode
    }, {
      baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1'
    })
    
    const reportId = res.data.id
    pollStatus(reportId)
  } catch (err: any) {
    error.value = err.response?.data?.detail || '报告生成失败，请稍后重试'
    loading.value = false
  }
}

const pollStatus = async (id: string) => {
  try {
    const res = await axios.get(`/report/${id}`, {
      baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1'
    })
    
    // 更新进度 UI
    if (res.data.progress !== undefined) {
      currentProgress.value = res.data.progress
    }
    if (res.data.progress_desc) {
      currentStatusText.value = res.data.progress_desc
    }

    if (res.data.status === 1) {
      currentProgress.value = 100
      report.value = res.data
      
      // 优先使用后端提供的结构化数据
      if (res.data.sections && Array.isArray(res.data.sections) && res.data.sections.length > 0) {
        console.log('Using structured sections from backend')
        sections.value = res.data.sections.map((s: any, i: number) => ({
          ...s,
          expanded: i < 2
        }))
      } else {
        console.log('Falling back to frontend parsing')
        sections.value = parseSections(res.data.content)
      }
      
      loading.value = false
      reportStore.setReport(id, res.data.content)
      
      // If we are currently on the 'loading' route, replace history with the actual report ID
      if (route.params.id === 'loading') {
        router.replace(`/report/${id}`)
      }
    } else if (res.data.status === 2) {
      error.value = res.data.error_msg || 'AI 解析失败'
      loading.value = false
    } else {
      // Still generating, poll again after 2 seconds
      setTimeout(() => pollStatus(id), 2000)
    }
  } catch (err) {
    error.value = '无法获取报告状态'
    loading.value = false
  }
}

const shareReport = () => {
  showPoster.value = true
}

const retry = () => {
  router.push('/')
}

onMounted(() => {
  if (route.params.id === 'loading') {
    generateReport()
  } else {
    pollStatus(route.params.id as string)
  }
})
</script>

<style scoped>
.section-content :deep(p) {
  margin-bottom: 1rem;
}
.section-content :deep(h4) {
  font-weight: bold;
  margin-top: 1.5rem;
  margin-bottom: 0.5rem;
  color: var(--xingwen-dark);
}
</style>
